[package]
name = "meilisearch-sdk"
version = "0.15.0"
authors = ["Mubelotix <mubelotix@gmail.com>"]
edition = "2018"
description = "Rust wrapper for the Meilisearch API. Meilisearch is a powerful, fast, open-source, easy to use and deploy search engine."
license = "MIT"
readme  = "README.md"
repository = "https://github.com/meilisearch/meilisearch-sdk"

[dependencies]
async-trait = "0.1.51"
iso8601-duration = "0.1.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3.7", features = ["serde-well-known", "formatting", "parsing"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures = "0.3"
isahc = { version = "1.0", features = ["http2", "text-decoding"], default_features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.47"
web-sys = { version = "0.3", features = ["RequestInit", "Headers", "Window", "Response", "console"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[features]
default = ["isahc-static-curl", "sync"]
isahc-static-curl = ["isahc/static-curl"]
sync = []

[dev-dependencies]
env_logger = "0.9"
futures-await-test = "0.3"
futures = "0.3"
mockito = "0.31.0"
meilisearch-test-macro = { path = "meilisearch-test-macro" }
tokio = { version = "1", features = ["rt", "macros"] }

# The following dependencies are required for examples
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
yew = "0.18"
lazy_static = "1.4"
web-sys = "0.3"
console_error_panic_hook = "0.1"

[[example]]
name = "web_app"
crate-type = ["cdylib", "rlib"]
required-features = ["sync"]
path = "examples/web_app/src/lib.rs"
